# Generated by Django 4.0.3 on 2022-06-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='dep_decription',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doc_name',
            field=models.CharField(max_length=255),
        ),
    ]
